name: model
description: Chat application model (gRPC and Protos)
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.0.0