name: grpc_chat_flutter
description: >-
    Simple Flutter Chat application for all supported platforms 
    with gRPC and ProtocolBuffers includes server service.
repository: https://github.com/santiihoyos/gRPC_Chat_flutter
issue_tracker: https://github.com/santiihoyos/gRPC_Chat_flutter/issues
documentation: https://santiihoyos.github.io/gRPC_Chat_flutter
version: 1.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  model:
    path: model
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.0.12
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  logger: any
  lottie: ^1.2.1
  grpc:
  protobuf:
  fixnum: ^1.0.0
  build_grpc_channel: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0

flutter:

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/icons/
    - assets/images/avatar/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
