name: server
description: Server services for Chat application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0' #Dart version

dependencies:
  grpc:
  protobuf:
  fixnum: ^1.0.0
  model:
    path: ../model

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
